# Generated by Django 2.2.8 on 2019-12-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='body',
            field=models.TextField(max_length=2000),
        ),
    ]
