# Generated by Django 2.2.8 on 2019-12-22 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('text_query', '0002_auto_20191222_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_query.Query')),
            ],
        ),
    ]
